name: Deploy

on:
    workflow_run:
        workflows: ['Build']
        types: [completed]
  
jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull docker image
      run: sudo docker pull himanshudangwal/react-game:latest
    - name: Delete old container
      run: sudo docker rm -f react-container || true
    - name: Start the new container
      run: sudo docker run -d -p 5173:5173 --name react-container himanshudangwal/react-game